{{- include "helm-library.configmap" (list . "bin-schedule.configmap") -}}
{{- define "bin-schedule.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  ADDRESS: {{ quote .Values.container.address }}
  POSTCODE: {{ quote .Values.container.postcode }}
  EMAILS: {{ quote .Values.container.emails }}
  SMTP_HOST: {{ quote .Values.container.smtpHost }}
  SMTP_USER: {{ quote .Values.container.smtpUser }}
  SMTP_PASSWORD: {{ quote .Values.container.smtpPassword }}
{{- end -}}
