{{- include "helm-library.configmap" (list . "bin-schedule.configmap") -}}
{{- define "bin-schedule.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  SMTP_HOST: {{ quote .Values.container.smtpHost }}
  SMTP_PORT: {{ quote .Values.container.smtpPort }}
{{- end -}}
