{{- include "helm-library.configmap" (list . "bin-schedule.configmap") -}}
{{- define "bin-schedule.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  REDIS_HOST: {{ quote .Values.container.redisHost }}
  MESSAGE_HOST: {{ quote .Values.container.messageHost }}  
  MESSAGE_EXCHANGE: {{ quote .Values.container.messageExchange }}
{{- end -}}
