{{- include "helm-library.secret" (list . "live-scores-publisher.secret") -}}
{{- define "live-scores-publisher.secret" -}}
stringData:
  ADDRESS: {{ quote .Values.container.address }}
  POSTCODE: {{ quote .Values.container.postcode }}
  EMAILS: {{ quote .Values.container.emails }}
  SMTP_HOST: {{ quote .Values.container.smtpHost }}
  SMTP_USER: {{ quote .Values.container.smtpUser }}
  SMTP_PASSWORD: {{ quote .Values.container.smtpPassword }}
{{- end -}}
