environment: production
name: bin-schedule
image: bin-schedule

container:
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  emails: test@test.com
  smtpHost: host.com
  smtpUser: user
  smtpPassword: password
  postcode: ab1 1ab
  address: home

secret:
  type: Opaque

cronJob:
  schedule: "30 7 * * *" # 7:30am every day
  concurrencyPolicy: Forbid
  restartPolicy: Never
