environment: production
name: bin-schedule
image: bin-schedule

container:
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  emails:
  smtpHost:
  smtpUser:
  smtpPassword:
  postcode:
  address:

secret:
  type: Opaque

cronJob:
  schedule: "30 7 * * *" # 7:30am every day
  concurrencyPolicy: Forbid
  restartPolicy: Never
