environment: production
name: bin-schedule
image: bin-schedule

container:
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 300Mi
  limitCpu: 200m
  smtpHost: smtp-mail.outlook.com
  smtpPort: 587

secret:
  secretsPath: /bin-schedule

cronJob:
  schedule: "30 7 * * *" # 7:30am every day
  concurrencyPolicy: Forbid
  restartPolicy: Never
  successfulJobsHistoryLimit: 1
