environment: production
name: bin-schedule
image: bin-schedule

container:
  requestMemory: 300Mi
  requestCpu: 100m
  limitMemory: 300Mi
  smtpHost: smtp-mail.outlook.com
  smtpPort: 587
  readOnlyRootFilesystem: false

secret:
  secretsPath: /bin-schedule

cronJob:
  schedule: "30 7 * * *" # 7:30am every day
  concurrencyPolicy: Forbid
  restartPolicy: Never
  successfulJobsHistoryLimit: 1
