environment: production
name: bin-schedule
image: bin-schedule

container:
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  emails:
  smtpHost:
  smtpUser:
  smtpPassword:
  postcode:
  address:

deployment: {}

secret:
  type: Opaque
